# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Backup .env
        run: |
          if [ -f .env ]; then
            cp .env /tmp/Instagram-Backend.env
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore .env
        run: |
          if [ -f /tmp/Instagram-Backend.env ]; then
            cp /tmp/Instagram-Backend.env .env
          fi

      - name: Check .env
        run: |
          if [ -f .env ]; then
            echo ".env file exists"
          else
            echo ".env file is missing"
            exit 1
          fi

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build --if-present

      - name: Restart Backend
        run: sudo pm2 restart Backend
